
namespace SakuraConnect.Shared.Models.Messaging.Ai
{
	/// <summary>
	/// The comment metadata
	/// </summary>
	public class Comment
    {
        /// <summary>
        /// The user this comment is responding to
        /// </summary>
        public string RespondTo { get; set; } = "";

		/// <summary>
		/// The comment generated by the AI
		/// </summary>
		public string Text { get; set; } = "";
	}
}
