
using Sakura.Live.ThePanda.Core.Interfaces;

namespace SakuraConnect.Streamer.Services.Ai
{
    /// <summary>
    /// Defines the character of the ai
    /// </summary>
    public class AiCharacterService : IAiCharacterService
    {
        // Dependencies
        readonly ISettingsService _settingsService;

        ///
        /// <inheritdoc />
        ///
        public string Name { get; set; } = "";

        ///
        /// <inheritdoc />
        ///
        public string Character { get; set; } = "You are a vtuber";

        ///
        /// <inheritdoc />
        ///
        public string GreetingStyle { get; set; } = "Act cute";

        /// <summary>
        /// Limits the number of words that can be generated by the ai
        /// </summary>
        public int WordLimit { get; set; } = 50;

        /// <summary>
        /// Creates a new instance of <see cref="AiCharacterService" />
        /// </summary>
        /// <param name="settingsService"></param>
        public AiCharacterService(ISettingsService settingsService)
        {
            _settingsService = settingsService;
            LoadSettings();
        }

        ///
        /// <inheritdoc />
        ///
        public string GetGreetingPrompt() {
            SaveSettings();
            return $"{Character}. {GreetingStyle}";
        }

        ///
        /// <inheritdoc />
        ///
        public string GetPersonalityPrompt()
        {
            SaveSettings();
            return $"{Character}";
        }

        ///
        /// <inheritdoc />
        ///
        public void SaveSettings()
        {
        }

        ///
        /// <inheritdoc />
        ///
        public void LoadSettings()
        {
         
        }
    }
}
